/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aula3.Exercicio3;

import javax.swing.JOptionPane;

/**
 *
 * @author fabio
 */
public class MainFuncionario extends javax.swing.JFrame {
    Funcionario funcionario = null;
    
    /**
     * Creates new form MainFuncionario
     */
    public MainFuncionario() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        txtCracha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnMostrar3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtValorDesconto = new javax.swing.JTextField();
        pValores = new javax.swing.JPanel();
        lblValorHora = new javax.swing.JLabel();
        txtValorHora = new javax.swing.JTextField();
        lblQtdeHora = new javax.swing.JLabel();
        txtQtdeHora = new javax.swing.JTextField();
        lblSalario = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        cbTipoVinculo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CADASTRO DE FUNCIONARIOS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, 46));

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        txtCracha.setText("123456");
        txtCracha.setToolTipText("");
        getContentPane().add(txtCracha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 242, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Cracha:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 53, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 53, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Tipo Vinculo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 84, -1));

        txtNome.setText("Fabio Colombini");
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 118, -1));

        btnMostrar3.setText("Sair");
        btnMostrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrar3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, -1, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Valor Desconto:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 84, -1));

        txtValorDesconto.setText("10");
        getContentPane().add(txtValorDesconto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 77, -1));

        pValores.setBorder(javax.swing.BorderFactory.createTitledBorder("Valores"));

        lblValorHora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValorHora.setText("Valor Hora:");

        txtValorHora.setText("100");
        txtValorHora.setEnabled(false);

        lblQtdeHora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblQtdeHora.setText("Quantidade hora:");

        txtQtdeHora.setText("10");
        txtQtdeHora.setEnabled(false);

        lblSalario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSalario.setText("Salário:");

        txtSalario.setText("100");

        javax.swing.GroupLayout pValoresLayout = new javax.swing.GroupLayout(pValores);
        pValores.setLayout(pValoresLayout);
        pValoresLayout.setHorizontalGroup(
            pValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pValoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pValoresLayout.createSequentialGroup()
                            .addComponent(lblSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pValoresLayout.createSequentialGroup()
                            .addComponent(lblValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pValoresLayout.createSequentialGroup()
                        .addComponent(lblQtdeHora, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQtdeHora, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        pValoresLayout.setVerticalGroup(
            pValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pValoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorHora)
                    .addComponent(txtValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQtdeHora)
                    .addComponent(txtQtdeHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSalario)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(pValores, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, 150));

        cbTipoVinculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Horista" }));
        cbTipoVinculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoVinculoActionPerformed(evt);
            }
        });
        getContentPane().add(cbTipoVinculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        JOptionPane.showMessageDialog(rootPane, funcionario.imprimir());
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        int cracha = Integer.parseInt(txtCracha.getText());
        char tipoVinculo = cbTipoVinculo.getSelectedItem().toString().charAt(0);
        float salario = Float.parseFloat(txtSalario.getText());
        float valorDesconto = Float.parseFloat(txtValorDesconto.getText());
        float valorHora = Float.parseFloat(txtValorHora.getText());
        float qtdeHora = Float.parseFloat(txtQtdeHora.getText()); 
            
        if (tipoVinculo == 'N') {
           funcionario = new Funcionario(cracha, txtNome.getText(), tipoVinculo, salario, valorDesconto);
           //funcionario = new Funcionario(cracha, txtNome.getText(), tipoVinculo, 0, 0, valorDesconto); 
        } else {
            funcionario = new Funcionario(cracha, txtNome.getText(), tipoVinculo, valorHora, qtdeHora, valorDesconto);
        }
        
        JOptionPane.showMessageDialog(rootPane, funcionario.getNome()+" cadastrado com sucesso!");
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnMostrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrar3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnMostrar3ActionPerformed

    private void cbTipoVinculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoVinculoActionPerformed
        if (cbTipoVinculo.getSelectedIndex() == 0) {
            txtValorHora.setEnabled(false);
            txtQtdeHora.setEnabled(false);
            txtSalario.setEnabled(true);
        } else {
            txtSalario.setEnabled(false);
            txtValorHora.setEnabled(true);
            txtQtdeHora.setEnabled(true);
        }
    }//GEN-LAST:event_cbTipoVinculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnMostrar3;
    private javax.swing.JComboBox<String> cbTipoVinculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblQtdeHora;
    private javax.swing.JLabel lblSalario;
    private javax.swing.JLabel lblValorHora;
    private javax.swing.JPanel pValores;
    private javax.swing.JTextField txtCracha;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtQtdeHora;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JTextField txtValorDesconto;
    private javax.swing.JTextField txtValorHora;
    // End of variables declaration//GEN-END:variables
}
